### ISSUE TITLE
Market Announcements

### ISSUE THREAD

**Issue by chx2** [tipoff/locations#94]
Markets should be able to be assigned announcements. There would need to be a message injected into a base announcement partial that would then be inserted into the base layout.

An example of an announcement would be a specific location closing due to COVID restrictions. While the announcement affects the local market, it would not affect other markets or locations. Besides updated migrations, there should probably be a Nova resource setup for this to toggle the announcment on/off including the content to display in the announcement.

**Comment by drewroberts** [comment]
Chris, could you work on this over the next week as you're creating the Layouts in issue #100
